name: Deploy Angular 2025 Archive
on:
  push:
    branches:
      - src/personal-website-2025

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: |
          npx ng run SuryaRaj:prerender -- --base-href /personal-website-2025/
          node scripts/generate-sitemap.js
          cp dist/SuryaRaj/browser/index.html dist/SuryaRaj/browser/404.html


      - name: Deploy to Main Branch Subdirectory
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: dist/SuryaRaj/browser
          target-folder: personal-website-2025
          clean: false
