name: Node.js CI

on:
  push:
    branches: [ "personal-website-2020-dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      working-directory: ./personal-website-2020
      run: yarn install

    - name: Build
      working-directory: ./personal-website-2020
      run: yarn build --base-href=/personal-website-2020/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: main
        folder: personal-website-2020/dist
        target-folder: personal-website-2020